name: Build Images
on:
  push:
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
        - 'arm64'
        - 'x86-64'
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup mkosi
      uses: systemd/mkosi@v24.3
    - name: Summary
      run: |
        sudo mkosi --distribution=debian summary
    - name: Build Image
      run: |
        sudo mkosi genkey
        sudo mkosi --root-password=toor --distribution=debian --architecture=${{ matrix.architecture }}
    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: incus-os-image-${{ matrix.architecture }}
        path: '*.raw'
        retention-days: 3
